### ISSUE TITLE
issue with UserAddOptions

### ISSUE THREAD

**Issue by derit** [swdee/etcdc#2]
error message

```
vendor\github.com\swdee\etcdc\auth.go:55:21: undefined: "go.etcd.io/etcd/auth/authpb".UserAddOptions
```

package

```
google.golang.org/grpc v1.29.1
go.etcd.io/etcd v3.3.25+incompatible
```

**Comment by swdee** [comment]
Hi,

This would be due to the package not including https://github.com/etcd-io/etcd/blob/master/api/authpb/auth.pb.go

Do you have a minimal code example I can run to reproduce the error and we could look at adding this in?

**Comment by derit** [comment]
this issue was solved 

i using this go.mod file for my go.mod package thanks

```
https://github.com/swdee/etcdc/blob/master/go.mod
```
